### ISSUE TITLE
按照要求安装完成后如下报错

### ISSUE THREAD

**Issue by xu-xiang** [ring04h/weakfilescan#5]
## \* scan http://wuyun.org start

Traceback (most recent call last):
  File "wyspider.py", line 17, in <module>
    print json.dumps(start_wyspider(sys.argv[1]), indent=2)
  File "/weakfilescan/controller.py", line 41, in start_wyspider
    link_datas = GetAllLink(siteurl).start()
  File "/weakfilescan/libs/GetAllLink.py", line 47, in start
    response_obj = LinksParser(http_request_get(self.siteurl))
  File "/weakfilescan/common.py", line 170, in **init**
    self.baseurl = get_baseurl(self.url)
  File "/weakfilescan/common.py", line 31, in get_baseurl
    netloc = urlparse.urlparse(link).netloc
  File "/usr/lib64/python2.7/urlparse.py", line 142, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python2.7/urlparse.py", line 181, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by xu-xiang** [comment]
帮助问题错误导致。。。
python wyspider.py http://wuyun.org php

这边的http://去掉即可
